/*
 * Auto-generated Complete Registry for TypeScript Bundling
 * Generated on: 2026-01-22T06:26:12.416313
 * 
 * This file contains ALL 12 mappings and parsed YAML data.
 * Gets bundled into mera-app.js via TypeScript compilation.
 * 
 * This file is automatically generated by dev/py/registry_builder.py
 * Do not edit manually - your changes will be overwritten
 */

import { 
    NewUserWelcomeProgressManager, NewUserWelcomeComponentConfigSchema, NewUserWelcomeComponentProgressSchema, createInitialProgress as createInitialNewUserWelcomeProgress
} from '../components/cores/newUserWelcomeCore.js';
import { 
    MainMenuProgressManager, MainMenuComponentConfigSchema, MainMenuComponentProgressSchema, createInitialProgress as createInitialMainMenuProgress
} from '../components/cores/mainMenuCore.js';
import { 
    BasicTaskProgressManager, BasicTaskComponentConfigSchema, BasicTaskComponentProgressSchema, validateBasicTaskStructure, createInitialProgress as createInitialBasicTaskProgress
} from '../components/cores/basicTaskCore.js';

/**
 * MAPPING 1: Component Type to Class
 */
export const componentTypeMap = new Map<string, any>([
    ["new_user_welcome", NewUserWelcomeProgressManager],
    ["main_menu", MainMenuProgressManager],
    ["basic_task", BasicTaskProgressManager]
]);

/**
 * MAPPING 2: Component Type to Config Schema
 */
export const configSchemaMap = new Map<string, any>([
    ["new_user_welcome", NewUserWelcomeComponentConfigSchema],
    ["main_menu", MainMenuComponentConfigSchema],
    ["basic_task", BasicTaskComponentConfigSchema]
]);

/**
 * MAPPING 3: Component Type to Progress Schema
 */
export const progressSchemaMap = new Map<string, any>([
    ["new_user_welcome", NewUserWelcomeComponentProgressSchema],
    ["main_menu", MainMenuComponentProgressSchema],
    ["basic_task", BasicTaskComponentProgressSchema]
]);

/**
 * MAPPING 4: Component Type to Validator Function
 */
export const componentValidatorMap = new Map<string, Function>([
    ["basic_task", validateBasicTaskStructure]
]);

/**
 * MAPPING 5: Component Type to Initializer Function
 */
export const componentInitializerMap = new Map<string, Function>([
    ["new_user_welcome", createInitialNewUserWelcomeProgress],
    ["main_menu", createInitialMainMenuProgress],
    ["basic_task", createInitialBasicTaskProgress]
]);

/**
 * MAPPING 6: Component Registration Array
 * Used by component factory for instantiation
 */
export const componentRegistrations = [
    {
        componentClass: NewUserWelcomeProgressManager,
        configSchema: NewUserWelcomeComponentConfigSchema,
        progressSchema: NewUserWelcomeComponentProgressSchema,
        typeName: 'new_user_welcome'
    },
    {
        componentClass: MainMenuProgressManager,
        configSchema: MainMenuComponentConfigSchema,
        progressSchema: MainMenuComponentProgressSchema,
        typeName: 'main_menu'
    },
    {
        componentClass: BasicTaskProgressManager,
        configSchema: BasicTaskComponentConfigSchema,
        progressSchema: BasicTaskComponentProgressSchema,
        typeName: 'basic_task'
    }
];

/**
 * MAPPING 7: All Entity IDs (Lessons + Menus)
 */
export const allLessonIds = [0, 1, 12345, 12346, 12347, 12348];

/**
 * MAPPING 7.5: All Component IDs
 */
export const allComponentIds = [123456, 123457, 223456, 223457, 323456, 323457, 423456, 423457, 1000000, 1000001];

/**
 * Lesson Metrics Type
 */
export interface LessonMetrics {
    pageCount: number;
    componentCount: number;
    title: string;
    difficulty: string;
}

/**
 * MAPPING 7.75: Lesson Metrics
 * Maps lesson ID to page count and component count
 */
export const lessonMetrics = new Map<number, LessonMetrics>([
    [12348, { pageCount: 2, componentCount: 2, title: "Phishing Recognition Basics", difficulty: "beginner" }],
    [0, { pageCount: 1, componentCount: 1, title: "Main Menu", difficulty: "beginner" }],
    [12345, { pageCount: 2, componentCount: 2, title: "Phishing Recognition Basics", difficulty: "beginner" }],
    [1, { pageCount: 1, componentCount: 1, title: "Welcome to Mera", difficulty: "beginner" }],
    [12346, { pageCount: 2, componentCount: 2, title: "Phishing Recognition Basics", difficulty: "beginner" }],
    [12347, { pageCount: 2, componentCount: 2, title: "Phishing Recognition Basics", difficulty: "beginner" }]
]);

/**
 * MAPPING 8: Component ID to Type Map
 * Maps component ID (number) to component type string
 * Critical for progress migration - allows validation against correct schema
 */
export const componentIdToTypeMap = new Map<number, string>([
    [123456, "basic_task"],
    [123457, "basic_task"],
    [223456, "basic_task"],
    [223457, "basic_task"],
    [323456, "basic_task"],
    [323457, "basic_task"],
    [423456, "basic_task"],
    [423457, "basic_task"],
    [1000000, "main_menu"],
    [1000001, "new_user_welcome"]
]);

/**
 * MAPPING 8.5: Component ID to Lesson ID Map
 * Maps component ID (number) to the lesson ID that contains it
 * Used by progressIntegrity to find lesson configs for component validation
 */
export const componentToLessonMap = new Map<number, number>([
    [123456, 12345],
    [123457, 12345],
    [223456, 12346],
    [223457, 12346],
    [323456, 12347],
    [323457, 12347],
    [423456, 12348],
    [423457, 12348],
    [1000000, 0],
    [1000001, 1]
]);

/**
 * MAPPING 9: Domain-Lesson Map
 * Maps domain ID to array of lesson IDs in that domain
 */
export const domainLessonMap = new Map<number, number[]>([
    [1004, [12348]],
    [1001, [12345]],
    [1002, [12346]],
    [1003, [12347]]
]);

/**
 * MAPPING 10: Curriculum Data
 * Complete parsed curriculum structure
 */
const curriculumDataRaw = null;

/**
 * Curriculum Registry - provides methods for querying curriculum data
 */
export class CurriculumRegistry {
    constructor(
        private curriculum: any,
        private lessonIds: Set<number>,
        private domainMap: Map<number, number[]>,
        private componentIdToType: Map<number, string>,
        private componentToLesson: Map<number, number>
    ) {}
    
    hasEntity(entityId: number): boolean {
        return this.lessonIds.has(entityId);
    }

    hasLesson(lessonId: number): boolean {
        const metadata = lessonMetadata.find(l => l.id === lessonId);
        return metadata?.entityType === "lesson" || false;
    }

    hasMenu(menuId: number): boolean {
        const metadata = lessonMetadata.find(l => l.id === menuId);
        return metadata?.entityType === "menu" || false;
    }

    hasDomain(domainId: number): boolean {
        return this.domainMap.has(domainId);
    }

    getEntityPageCount(entityId: number): number {
        const metrics = lessonMetrics.get(entityId);
        if (!metrics) {
            throw new Error(
                `Entity ${entityId} not found in registry. ` +
                `Cannot determine page count.`
            );
        }
        return metrics.pageCount;
    }

    hasComponent(componentId: number): boolean {
        return this.componentIdToType.has(componentId);
    }

    getComponentType(componentId: number): string | undefined {
        return this.componentIdToType.get(componentId);
    }

    getAllComponentIds(): number[] {
        return Array.from(this.componentIdToType.keys());
    }

    getAllLessonIds(): number[] {
        return Array.from(this.lessonIds);
    }

    getAllDomainIds(): number[] {
        return Array.from(this.domainMap.keys());
    }

    getLessonsInDomain(domainId: number): number[] | undefined {
        return this.domainMap.get(domainId);
    }

    getLessonIdForComponent(componentId: number): number | undefined {
        return this.componentToLesson.get(componentId);
    }
}

export const curriculumData = new CurriculumRegistry(
    curriculumDataRaw,
    new Set(allLessonIds),
    domainLessonMap,
    componentIdToTypeMap,
    componentToLessonMap
);

/**
 * MAPPING 11: Domain Data
 * Array of all domain definitions
 */
export const domainData = [
  {
    "domain_id": 1003,
    "title": "Recognize & Respond to Threats",
    "description": "Identify phishing, social engineering, and surveillance, then respond appropriately",
    "pedagogical_focus": "Threat recognition and incident response for activist contexts",
    "lesson_count": 18,
    "estimated_weeks": 6,
    "order": 4,
    "key_outcomes": [
      "Recognize phishing attempts and social engineering",
      "Identify surveillance indicators",
      "Respond appropriately to device seizure",
      "Implement threat-appropriate security measures"
    ],
    "core_concept": "Threat modeling - recognize attacks and respond proportionally to actual risk"
  },
  {
    "domain_id": 1002,
    "title": "Lock Down Your Accounts",
    "description": "Secure existing accounts with strong passwords, 2FA, and proper device settings",
    "pedagogical_focus": "Basic account security and device hardening for everyday protection",
    "lesson_count": 20,
    "estimated_weeks": 7,
    "order": 2,
    "key_outcomes": [
      "Implement strong unique passwords with password manager",
      "Enable two-factor authentication on critical accounts",
      "Configure secure device settings (disable FaceID, auto-backup)",
      "Understand and manage app permissions"
    ],
    "core_concept": "Defense in depth - multiple layers of security on devices and accounts"
  },
  {
    "domain_id": 1001,
    "title": "Separate Your Identities",
    "description": "Learn to compartmentalize your digital life between activist and civilian identities",
    "pedagogical_focus": "Identity separation and account isolation to protect activist work from surveillance",
    "lesson_count": 20,
    "estimated_weeks": 7,
    "order": 1,
    "key_outcomes": [
      "Create separate activist and civilian email accounts",
      "Migrate sensitive accounts to protected identity",
      "Understand metadata risks in social media",
      "Maintain boundaries between identities"
    ],
    "core_concept": "Compartmentalization - assume civilian identity is compromised, protect activist identity"
  },
  {
    "domain_id": 1004,
    "title": "Recognize & Respond to Threats",
    "description": "Identify phishing, social engineering, and surveillance, and respond appropriately",
    "pedagogical_focus": "Threat recognition and incident response",
    "lesson_count": 18,
    "estimated_weeks": 6,
    "order": 4,
    "key_outcomes": [
      "Recognize phishing attempts and social engineering",
      "Identify surveillance indicators",
      "Respond appropriately to device seizure",
      "Implement threat-appropriate security measures"
    ]
  }
];

/**
 * MAPPING 12: Entity Metadata
 * Complete metadata for all entities (lessons and menus)
 */
export const lessonMetadata = [
  {
    "id": 12348,
    "path": "static/yaml/lessons/phishing-basics-4.yaml",
    "title": "Phishing Recognition Basics",
    "entityType": "lesson",
    "pageCount": 2,
    "componentCount": 2,
    "difficulty": "beginner",
    "estimatedMinutes": 8,
    "required": true,
    "domainId": 1004
  },
  {
    "id": 0,
    "path": "static/yaml/lessons/main_menu.yaml",
    "title": "Main Menu",
    "entityType": "lesson",
    "pageCount": 1,
    "componentCount": 1,
    "difficulty": "beginner",
    "estimatedMinutes": 1,
    "required": true,
    "domainId": null
  },
  {
    "id": 12345,
    "path": "static/yaml/lessons/phishing-basics.yaml",
    "title": "Phishing Recognition Basics",
    "entityType": "lesson",
    "pageCount": 2,
    "componentCount": 2,
    "difficulty": "beginner",
    "estimatedMinutes": 8,
    "required": true,
    "domainId": 1001
  },
  {
    "id": 1,
    "path": "static/yaml/lessons/welcome_menu.yaml",
    "title": "Welcome to Mera",
    "entityType": "lesson",
    "pageCount": 1,
    "componentCount": 1,
    "difficulty": "beginner",
    "estimatedMinutes": 5,
    "required": true,
    "domainId": null
  },
  {
    "id": 12346,
    "path": "static/yaml/lessons/phishing-basics-2.yaml",
    "title": "Phishing Recognition Basics",
    "entityType": "lesson",
    "pageCount": 2,
    "componentCount": 2,
    "difficulty": "beginner",
    "estimatedMinutes": 8,
    "required": true,
    "domainId": 1002
  },
  {
    "id": 12347,
    "path": "static/yaml/lessons/phishing-basics-3.yaml",
    "title": "Phishing Recognition Basics",
    "entityType": "lesson",
    "pageCount": 2,
    "componentCount": 2,
    "difficulty": "beginner",
    "estimatedMinutes": 8,
    "required": true,
    "domainId": 1003
  }
];

console.log(`Mera Registry loaded with all 12 mappings:`);
console.log(`  - ${componentRegistrations.length} component types`);
console.log(`  - ${allLessonIds.length} entities (lessons + menus)`);
console.log(`  - ${allComponentIds.length} component IDs`);
console.log(`  - ${componentIdToTypeMap.size} component ID->type mappings`);
console.log(`  - ${domainLessonMap.size} domains`);
