/*
 * Auto-generated Complete Registry for TypeScript Bundling
 * Generated on: 2025-12-14T09:18:27.688041
 * 
 * This file contains ALL 11 mappings and parsed YAML data.
 * Gets bundled into mera-app.js via TypeScript compilation.
 * 
 * This file is automatically generated by dev/py/registry_builder.py
 * Do not edit manually - your changes will be overwritten
 */

import { z } from 'zod';
import type { BaseComponentProgressManager } from '../components/cores/baseComponentCore.js';

// No components discovered yet

export interface ComponentRegistration {
    componentClass: any;
    configSchema: z.ZodType<any>;
    progressSchema: z.ZodType<any>;
    typeName: string;
}

export interface LessonMetrics {
    pageCount: number;
    componentCount: number;
    title: string;
    difficulty: string;
}

/**
 * MAPPING 1: Component Registrations
 * Array of all component registrations with classes and schemas
 */
export const componentRegistrations: ComponentRegistration[] = [

];

/**
 * MAPPING 2: Component Type Map
 * Maps component type string to component class
 */
export const componentTypeMap = new Map<string, any>([

]);

/**
 * MAPPING 3: Config Schema Map
 * Maps component type string to config schema
 */
export const configSchemaMap = new Map<string, z.ZodType<any>>([

]);

/**
 * MAPPING 4: Progress Schema Map
 * Maps component type string to progress schema
 */
export const progressSchemaMap = new Map<string, z.ZodType<any>>([

]);

/**
 * MAPPING 4.5: Component Validator Map
 * Maps component type string to validator function
 * Used by progressIntegrity to validate component progress against config
 */
export const componentValidatorMap = new Map<string, any>([

]);

/**
 * MAPPING 4.6: Component Initializer Map
 * Maps component type string to createInitialProgress function
 * Used by progressIntegrity to initialize missing/new components with defaults
 */
export const componentInitializerMap = new Map<string, () => any>([

]);

/**
 * MAPPING 5: All Entity IDs
 * Set of all valid entity IDs in the system (lessons and menus)
 */
export const allLessonIds = [12345];

/**
 * MAPPING 6: All Component IDs
 * Set of all component IDs used across all entities
 */
export const allComponentIds = [123456, 123457];

/**
 * MAPPING 7: Entity Metrics Map
 * Maps entity ID to metrics (page count, component count, etc.)
 */
export const lessonMetrics = new Map<number, LessonMetrics>([
    [12345, { pageCount: 2, componentCount: 2, title: "Phishing Recognition Basics", difficulty: "beginner" }]
]);

/**
 * MAPPING 8: Component ID to Type Map
 * Maps component ID (number) to component type string
 * Critical for progress migration - allows validation against correct schema
 */
export const componentIdToTypeMap = new Map<number, string>([
    [123456, "basic_task"],
    [123457, "basic_task"]
]);

/**
 * MAPPING 8.5: Component ID to Lesson ID Map
 * Maps component ID (number) to the lesson ID that contains it
 * Used by progressIntegrity to find lesson configs for component validation
 */
export const componentToLessonMap = new Map<number, number>([
    [123456, 12345],
    [123457, 12345]
]);

/**
 * MAPPING 9: Domain-Lesson Map
 * Maps domain ID to array of lesson IDs in that domain
 */
export const domainLessonMap = new Map<number, number[]>([
    [1001, [12345]]
]);

/**
 * MAPPING 10: Curriculum Data
 * Complete parsed curriculum structure
 */
const curriculumDataRaw = null;

/**
 * Curriculum Registry - provides methods for querying curriculum data
 */
export class CurriculumRegistry {
    constructor(
        private curriculum: any,
        private lessonIds: Set<number>,
        private domainMap: Map<number, number[]>,
        private componentIdToType: Map<number, string>,
        private componentToLesson: Map<number, number>
    ) {}
    
    hasEntity(entityId: number): boolean {
        return this.lessonIds.has(entityId);
    }

    hasLesson(lessonId: number): boolean {
        const metadata = lessonMetadata.find(l => l.id === lessonId);
        return metadata?.entityType === "lesson" || false;
    }

    hasMenu(menuId: number): boolean {
        const metadata = lessonMetadata.find(l => l.id === menuId);
        return metadata?.entityType === "menu" || false;
    }

    hasDomain(domainId: number): boolean {
        return this.domainMap.has(domainId);
    }

    getEntityPageCount(entityId: number): number {
        const metrics = lessonMetrics.get(entityId);
        if (!metrics) {
            throw new Error(
                `Entity ${entityId} not found in registry. Cannot determine page count.`
            );
        }
        return metrics.pageCount;
    }

    hasComponent(componentId: number): boolean {
        return this.componentIdToType.has(componentId);
    }

    getComponentType(componentId: number): string | undefined {
        return this.componentIdToType.get(componentId);
    }

    getAllComponentIds(): number[] {
        return Array.from(this.componentIdToType.keys());
    }

    getAllLessonIds(): number[] {
        return Array.from(this.lessonIds);
    }

    getAllDomainIds(): number[] {
        return Array.from(this.domainMap.keys());
    }

    getLessonIdForComponent(componentId: number): number | undefined {
        return this.componentToLesson.get(componentId);
    }
}

export const curriculumData = new CurriculumRegistry(
    curriculumDataRaw,
    new Set(allLessonIds),
    domainLessonMap,
    componentIdToTypeMap,
    componentToLessonMap
);

/**
 * MAPPING 11: Domain Data
 * Array of all domain definitions
 */
export const domainData = [];

/**
 * MAPPING 12: Entity Metadata
 * Complete metadata for all entities (lessons and menus)
 */
export const lessonMetadata = [
  {
    "id": 12345,
    "path": "static/yaml/lessons/phishing-basics.yaml",
    "title": "Phishing Recognition Basics",
    "entityType": "lesson",
    "pageCount": 2,
    "componentCount": 2,
    "difficulty": "beginner",
    "estimatedMinutes": 8,
    "required": true,
    "domainId": 1001
  }
];

console.log(`Mera Registry loaded with all 12 mappings:`);
console.log(`  - ${componentRegistrations.length} component types`);
console.log(`  - ${allLessonIds.length} entities (lessons + menus)`);
console.log(`  - ${allComponentIds.length} component IDs`);
console.log(`  - ${componentIdToTypeMap.size} component ID->type mappings`);
console.log(`  - ${domainLessonMap.size} domains`);
